Repository BME-MIT-IET/iet-hf2021-elia, pull requests merged in 2021-05, with the labels that each got.

#3 Added development mode
  config.json
  source/Elia.js
  source/components/core/DataComponent.js
Labels: enhancement

#16 Fixed PinCommand wrong function call
  source/commands/text/PinCommand.js
Labels: bug

#2 Unit testing
  .gitignore
  package.json
  source/components/music/MusicQueue.js
  test/unit/musicqueue/continuePlayingMusic.test.js
  test/unit/musicqueue/pauseMusic.test.js
  test/unit/musicqueue/playMusic.test.js
  test/unit/musicqueue/playMusicFromQueue.test.js
  test/unit/musicqueue/skipSong.test.js
  test/unit/musicqueue/stopMusic.test.js
  test/unit/utility/urlChecker.test.js
Labels: enhancement

#15 Bdd testing
  .gitignore
  IET-HF.md
  doc/bdd-testing.md
  test/bdd/Pipfile
  test/bdd/main.py
Labels: enhancement

#11 Static code analysis
  source/commands/voice/music/PlayCommand.js
  source/components/music/MusicQueue.js
Labels: enhancement

#18 Improve CI
  .eslintrc.js
  package-lock.json
  package.json
Labels: enhancement

#21 Fixed some ESLint errors and warnings
  .eslintrc.js
  package-lock.json
  package.json
  source/Elia.js
  source/commands/Command.js
  source/commands/text/PollCommand.js
  source/commands/voice/music/PlayCommand.js
  source/components/music/MusicQueue.js
  test/unit/musicqueue/continuePlayingMusic.test.js
  test/unit/musicqueue/pauseMusic.test.js
  test/unit/musicqueue/playMusic.test.js
  test/unit/musicqueue/playMusicFromQueue.test.js
  test/unit/musicqueue/skipSong.test.js
  test/unit/musicqueue/stopMusic.test.js
  test/unit/utility/urlChecker.test.js
Labels: enhancement

#22 Added coverage to SonarCloud
  .github/workflows/sonarcloud.yml
  .github/workflows/test.yml
  .gitignore
  package.json
  sonar-project.properties
Labels: enhancement

#12 Documentation
  IET-HF.md
  doc/ci.md
  doc/nonfunctional-testing.md
Labels: documentation
